### ISSUE TITLE
car control loop infinito

### ISSUE THREAD

**Issue by renasiwnl** [goncalobsccosta/atlanticrp-reports#12]
ola goncalo, tive um problema no five m ha um dia e entao deletei o cache e quando tentei entrar no servidor o car control carregava infinitamente, quando acabava de dar download voltava tudo ao inicio e assim repetitivamente, tentei usar dados moveis ontem e consegui entrar no servidor, hoje ja me acontece o mesmo e nem com dados moveis esta a resultar, agora tentei outra vez e consehui entrar btw

**Comment by goncalobsccosta** [comment]
Fixed entao?

**Comment by renasiwnl** [comment]
yes, gracias

Gonçalo Costa ***@***.***> escreveu em qui., 26/10/2023 às
5:34 PM :
