### ISSUE TITLE
Banido por spawn de armas ao guardar arma no carro

### ISSUE THREAD

**Issue by andresant0ss** [goncalobsccosta/atlanticrp-reports#15]
Entrei na cidade fui guardar a arma no carro e levei ban automatico .
https://medal.tv/games/gta-v/clips/1ACuz2t2M9fLlX/d13378NhI5SI?invite=cr-MSxXNlYsMTc5Njg2MTUyLA

**Comment by goncalobsccosta** [comment]
Só levaste kick
