### ISSUE TITLE
sc aumenta 

### ISSUE THREAD

**Issue by prmc16** [goncalobsccosta/atlanticrp-reports#19]
https://medal.tv/pt/games/gta-v/clips/1ANDS2g8X9U7tD/d1337AjUcyiO?invite=cr-MSxuQUIsMTkyMTg0ODIwLA

https://medal.tv/pt/games/gta-v/clips/1ANtVTeH7AO80C/d1337zEgQoeB?invite=cr-MSxUZXAsMTkyMTg0ODIwLA

isto aconteceu me umas 10x

**Comment by goncalobsccosta** [comment]
vou fechar por falta de resposta
