### ISSUE TITLE
erro car control 22 

### ISSUE THREAD

**Issue by renasiwnl** [goncalobsccosta/atlanticrp-reports#21]
quando tento entrar no atlantic, chega a parte do car control 22 e comeca a baixar,porem quando chega ao fim, volta tudo do inicio e fica assim repetidamente, nao da nenhum erro, apenas baixa infinitamente

**Comment by goncalobsccosta** [comment]
boas, deve ser um problema do teu pc, falta de espaço ou algo do genero

**Comment by davim94** [comment]
boa noite qauando vou a entrar diz que nao da ie manda me vir pra esta pagina ... o que posso fazer ? obrigado
