### ISSUE TITLE
Perdi Os meus carros e motos

### ISSUE THREAD

**Issue by McHyp3r** [goncalobsccosta/atlanticrp-reports#29]
Entrei no server hoje e fui buscar um dos meus carros e diz que nao tenho carros e fui ver aos apreendidos e tambem nao estao la.

**Comment by goncalobsccosta** [comment]
Esse bug report não faz sentido, abre ticket no discord

**Comment by McHyp3r** [comment]
como abro ticket no discord?

**Comment by McHyp3r** [comment]
Ja consegui fui a outra garagem e ja consegui os meus carros obrigado na mesma
