### ISSUE TITLE
Erro ao entrar no servidor

### ISSUE THREAD

**Issue by guga39274** [goncalobsccosta/atlanticrp-reports#55]
Não consigo entrar no servidor pq o meu discord é demasiado recente.[
![AAAAA](https://github.com/user-attachments/assets/9ddf841a-8c2d-49ca-9f68-db91fcc7ab80)

**Comment by MinguitoLoko** [comment]
Não consigo entrar no servidor

**Comment by GoncaloGarrido2** [comment]
eu tmb não consigo :(
