### ISSUE TITLE
Loading Infinito

### ISSUE THREAD

**Issue by ganzas64** [goncalobsccosta/atlanticrp-reports#6]
Boas Gonçalo
Não sei se este será o canal certo, mas preciso da tua ajuda:
Desde hoje à tarde que não consigo entrar na cidade uma vez que não saio do vídeo inicial de entrada no Atlantico, tal como podes verificar no clip.
Para tentar corrigir o erro já desinstalei e voltei a instalar o FiveM, limpei inúmeras vezes a cache e reiniciei o PC também por diversas vezes. Apenas consegui entrar a seguir ao RR do servidor, mas como levei kick por inatividade (estava à pesca), voltou a acontecer a mesma situação.
Agradeço, se possível, a tua ajuda.

https://youtu.be/_Fw8k17bmzM

**Comment by goncalobsccosta** [comment]
Há mais gente com este bug, vou ver o que se passa, sim é o canal certo

**Comment by goncalobsccosta** [comment]
Corrigido no próximo restart
