### ISSUE TITLE
Failed to open packfile: ReadBulk

### ISSUE THREAD

**Issue by HugoHigherr** [goncalobsccosta/atlanticrp-reports#9]
Boa tarde, desde dos rr das 11:22 , não consigo entrar no servidor no qual dá este erro : "Couldn't load resource chat: Failed to open packfile: ReadBulk of header failed: Failed to fetch: Failed to add entry to local storage (download corrupted?)"

![Captura de ecrã 2023-10-24 181028](https://github.com/goncalobsccosta/atlanticrp-reports/assets/148897419/a2689074-d029-4938-a714-c424b5cb62ba)

**Comment by goncalobsccosta** [comment]
penso que esteja corrigido, obrigado pelo report
